### ISSUE TITLE
Running Issue

### ISSUE THREAD

**Issue by chewbyte** [Z4nzu/hackingtool#209] opened 2022-04-02 05:57 UTC
**Describe the bug**

I have installed this tool successfully though when i go to run it with <sudo hackingtool> or <hackingtool> it comes up with the error I have attached as a screenshot. Why would this be happening?

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/13176339/161368818-26bf3219-9ba7-4bab-a451-65d379c6d405.jpeg)

**Desktop (please complete the following information):**
 - OS: Kali

**Smartphone (please complete the following information):**
 - Device: rpi4

**Additional context**

**Comment by mak2033** [comment] 2022-04-02 08:52
same here

**Comment by chewbyte** [comment] 2022-04-02 10:08
Might try and rm then reinstall

**Comment by Swetsen** [comment] 2022-04-02 11:08
edit /usr/share/doc/hackingtool/tools/ddos.py on line 29 and add quotation marks around sockstype5.4.1

**Comment by Swetsen** [comment] 2022-04-02 11:09
Duplicate of #194 and essentially every single other issue

**Comment by chewbyte** [comment] 2022-04-03 03:38
Got it to work after a few removes and some missed "Sudo" commands here and there

**Comment by cclauss** [comment] 2022-06-12 19:56
Fixed in #176

**Comment by cclauss** [comment] 2023-03-04 06:59
Fixed in #176 (merged)
Please close this issue.

**Closed** 2023-03-04 11:54 UTC
