### ISSUE TITLE
Pip3 command not found

### ISSUE THREAD

**Issue by TwistedVision518** [Z4nzu/hackingtool#213] opened 2022-04-03 09:45 UTC
Noticed that when trying to run the "bash install.sh" command it removes python3 and installs python2.7 which does not support pip3 i dont think its supposed to remove that package

**Comment by cclauss** [comment] 2022-04-04 09:37
Python 2 died 824 days ago on 1/1/2020 so it is often no longer available in modern operating systems.

**Comment by cclauss** [comment] 2022-04-04 09:38
Please close this issue as it is a duplicate of #212

**Comment by goddardYYZ** [comment] 2022-04-26 20:06
This does not fix the issue but okay... With python3-pip the issue still persists.

**Closed** 2022-11-30 18:45 UTC
