### ISSUE TITLE
Enter Path (with Directory Name) >> /usr/local/sbin:/usr/local/bin:/usr/sbin: Traceback (most recent call last):   File "/usr/share/hackingtool/hackingtool.py", line 90, in <module>     with open(fpath, "w") as f:          ^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by kingkali07** [Z4nzu/hackingtool#371] opened 2023-06-18 15:25 UTC
Enter Path (with Directory Name) >> /usr/local/sbin:/usr/local/bin:/usr/sbin:
Traceback (most recent call last):
  File "/usr/share/hackingtool/hackingtool.py", line 90, in <module>
    with open(fpath, "w") as f:
         ^^^^^^^^^^^^^^^^

**Comment by Tamilanth** [comment] 2023-07-11 05:19
Please give a detailed log of the error,
Include more informations like how to reproduce this error, the platform you are on etc..

**Comment by cclauss** [comment] 2023-07-18 06:23
Duplicate of #372

**Comment by cclauss** [comment] 2023-07-22 08:39
@kingkali07 Can this issue be closed or is there a documentation todo?

**Comment by kingkali07** [comment] 2023-07-22 18:13
issue not closed brother getting same error

**Comment by kingkali07** [comment] 2023-07-22 18:46
![Screenshot_2023-07-23_00_10_59](https://github.com/Z4nzu/hackingtool/assets/136045841/2b0ef866-4792-4c2f-8dd3-53db48b22bf1)
 brothers please check this image this is the error

**Comment by kingkali07** [comment] 2023-07-22 18:46
> Please give a detailed log of the error, Include more informations like how to reproduce this error, the platform you are on etc..
![Screenshot_2023-07-23_00_10_59](https://github.com/Z4nzu/hackingtool/assets/136045841/1ca6cd0f-87b0-4792-85b3-7e1d4ce2c00b)

**Comment by kingkali07** [comment] 2023-07-22 18:47
> @kingkali07 Can this issue be closed or is there a documentation todo?
![Screenshot_2023-07-23_00_10_59](https://github.com/Z4nzu/hackingtool/assets/136045841/3c15dbd7-08ee-413d-82d3-3a18b53606d8)

**Comment by cclauss** [comment] 2023-07-22 20:41
What filepath did you enter?
The screens above make it look like an empty string was entered.

**Comment by kingkali07** [comment] 2023-07-23 02:03
I selected 1 manual  after showing this message can you tell me what can I do to solve this problem

**Comment by Tamilanth** [comment] 2023-07-23 02:55
@kingkali07 In the next step (after choosing the option of manual), it is asking for the path, where the tools can be installed. 

Looks lile you didn't gave any path as input

**Comment by kingkali07** [comment] 2023-07-23 05:15
ok thankyou brother can you tell me how to gave a path as input please

**Comment by Tamilanth** [comment] 2023-07-23 05:18
I suggest you to make it default by selecting 2

**Comment by Z4nzu** [comment] 2023-07-23 05:19
If you're selecting the Manual path option then provide a path like `/home/$USER/downloads` it could be any folder name in which all the tools will be stored.

**Comment by kingkali07** [comment] 2023-07-23 06:18
solved thankyou all

**Comment by cclauss** [comment] 2023-07-23 06:18
`$HOME/downloads` might be better on Ubuntu and Debian where $USER is undefined...

% `docker run --rm -it ubuntu:lunar bash`  # Jump into the current Ubuntu as user `root`
```
root@bd928f405d82:/# whoami
root
root@bd928f405d82:/# echo "/home/$USER/downloads"
/home//downloads  # $USER is undefined e.g. an empty string
root@bd928f405d82:/# echo "$HOME/downloads"
/root/downloads
```
docker run --rm --user ubuntu -it ubuntu:lunar bash  # Jump into the current Ubuntu as user`ubuntu`
```
ubuntu@d9869bc6bbdd:/$ whoami
ubuntu
ubuntu@d9869bc6bbdd:/$ echo /home/$USER/downloads
/home//downloads
ubuntu@d9869bc6bbdd:/$ echo $HOME/downloads
/home/ubuntu/downloads
```
---
% `docker run --rm -it debian:bookworm bash`  # Jump into the current **Debian** as user `root`
```
...
```

**Comment by cclauss** [comment] 2023-07-23 06:21
@kingkali07 If this issue is solved then please close it and also #372.

**Closed** 2023-07-23 06:22 UTC
