### ISSUE TITLE
Enter Path (with Directory Name) >>  getting error plase solve this problem

### ISSUE THREAD

**Issue by kingkali07** [Z4nzu/hackingtool#372] opened 2023-06-18 15:26 UTC
Enter Path (with Directory Name) >> /usr/local/sbin:/usr/local/bin:/usr/sbin:
Traceback (most recent call last):
  File "/usr/share/hackingtool/hackingtool.py", line 90, in <module>
    with open(fpath, "w") as f:
         ^^^^^^^^^^^^^^^^

**Comment by cclauss** [comment] 2023-07-18 06:23
Duplicate of #371

**Comment by cclauss** [comment] 2023-07-22 08:39
@kingkali07 Can this issue be closed or is there a documentation todo?

**Closed** 2023-07-23 06:23 UTC
